language: clojure
sudo: false
before_script: mkdir checkouts && cd checkouts && git clone https://github.com/clojusc/mesomatic.git
jdk:
  - oraclejdk8
  #- oraclejdk7
  - openjdk6
  - openjdk7
  #- openjdk8
#addons:
#  apt:
#    sources:
#      - 
notifications:
  email:
      - oubiwann@gmail.com

